### ISSUE TITLE
maybe older code style in function `lv_qrcode_create`

### ISSUE THREAD

**Issue by fan12398** [lvgl/lv_lib_qrcode#1]
In lv_qrcode.c, function `lv_qrcode_create` calls `LV_IMG_BUF_SIZE_INDEXED_1BIT` and `LV_ASSERT_MEM`，however, I could not find the declarations or definitions in master lvgl respo.
```
lv_obj_t * lv_qrcode_create(lv_obj_t * parent, lv_coord_t size, lv_color_t dark_color, lv_color_t light_color)
{
    uint32_t buf_size = LV_IMG_BUF_SIZE_INDEXED_1BIT(size, size);
    uint8_t * buf = lv_mem_alloc(buf_size);
    LV_ASSERT_MEM(buf);
```
So, I replace them with `LV_CANVAS_BUF_SIZE_INDEXED_1BIT` and `lv_mem_assert`, is that right?
```
lv_obj_t * lv_qrcode_create(lv_obj_t * parent, lv_coord_t size, lv_color_t dark_color, lv_color_t light_color)
{
   uint32_t buf_size = LV_CANVAS_BUF_SIZE_INDEXED_1BIT(size, size);
   uint8_t * buf = lv_mem_alloc(buf_size);
   lv_mem_assert(buf);
```

**Comment by embeddedt** [comment]
I believe that's correct. Probably the code just wasn't updated for the latest version. Can you send a pull request?

**Comment by kisvegabor** [comment]
I've worked with `dev-6.1` where `LV_IMG_BUF_SIZE_...` haven't existed yet and `lv_mem_assert` has changed.

A PR would be really welcome!

**Comment by kisvegabor** [comment]
The PR is merged so I close this issue.

Thank you!
