### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by gadget-man** [lvgl/lv_lib_qrcode#3]
I'm unable to build my firmware when adding the QR Code Lib, using the example code provided. 
I get the following error:

src/lv_lib_qrcode/lv_qrcode.c:52:4: error: implicit declaration of function 'lv_mem_assert' [-Werror=implicit-function-declaration]
    lv_mem_assert(buf);
    ^

I'm using lvl 6.1.2, and embedding the code within mongoose-os.

**Comment by kisvegabor** [comment]
Do you use the latest version of the QR code library?

**Comment by gadget-man** [comment]
Yes, I only cloned it yesterday. I managed to get it working by using the following:
`lv_obj_t * lv_qrcode_create(lv_obj_t * parent, lv_coord_t size, lv_color_t dark_color, lv_color_t light_color)
{
    lv_color_t cbuf[LV_CANVAS_BUF_SIZE_INDEXED_1BIT(size, size)];

   lv_obj_t * canvas = lv_canvas_create(parent, NULL);
   if(canvas == NULL) return NULL;

   lv_canvas_set_buffer(canvas, cbuf, size, size, LV_IMG_CF_INDEXED_1BIT);
   lv_canvas_set_palette(canvas, 0, dark_color);
   lv_canvas_set_palette(canvas, 1, light_color);

   return canvas;

}`

**Comment by kisvegabor** [comment]
I've checked it and fixed it here: 2140ed2

Can you confirm if it's working well?

**Comment by eduardo-carletti** [comment]
> I've checked it and fixed it here: [2140ed2](https://github.com/lvgl/lv_lib_qrcode/commit/2140ed203f128ac8ffa7c850ad46925cf6c83da7)
> 
> Can you confirm if it's working well?

I had the same issue and this modification didn't work. Changed the LV_ASSERT_MEM by function lv_mem_assert and it compiled.

**Comment by kisvegabor** [comment]
I updated it here: https://github.com/lvgl/lv_lib_qrcode/commit/548dc861ef4bd4bdabf53aaa44631f8779c9e235

Is it okay now?

**Comment by detly** [comment]
I had the same issue; 548dc861ef4bd4bdabf53aaa44631f8779c9e235 still errorred out on `lv_memcpy()` but  d7ea64dfc95beee487c4d4e26a3b055066ce850d fixed that. It compiles cleanly against lvgl 7.1.0 now.

**Comment by kisvegabor** [comment]
Great! Thanks for the feedback!
